"""Main application for the Cybersecurity and Deepfake Multi-Agent System."""

from workflow.graph import build_graph
import time
import textwrap
import shutil


# ============================================================
# TEXT WRAPPING
# ============================================================

def wrap_text(
    text: str,
    width: int = 65,
    continuation_indent: int = 0,
) -> list[str]:
    """
    Wrap text according to the available terminal width.

    Args:
        text: Text to wrap.
        width: Preferred maximum width.
        continuation_indent: Space reserved for indentation.

    Returns:
        Wrapped text lines.
    """

    terminal_width = shutil.get_terminal_size(
        fallback=(100, 24)
    ).columns

    # Reserve one extra character so wrapped text does not
    # touch the rightmost edge of the terminal.
    available_width = (
        terminal_width
        - continuation_indent
        - 1
    )

    # Keep a sensible minimum while never exceeding the terminal.
    available_width = max(
        20,
        min(
            width,
            available_width,
        ),
    )

    return textwrap.wrap(
        str(text),
        width=available_width,
        break_long_words=False,
        break_on_hyphens=False,
    )


# ============================================================
# PRINT FINAL RESULT
# ============================================================

def print_result(
    result: dict,
) -> None:
    """
    Display the final result generated by the MAS workflow.

    The final response is already formatted by graph.py.
    Therefore, this function only displays that response and
    does not print separate routing or specialist sections.
    """

    final_response = result.get(
        "final_response",
        "",
    )

    if final_response:
        print(
            "\n" + final_response
        )
    else:
        print(
            "\nNo final analysis was generated."
        )


# ============================================================
# MAIN APPLICATION
# ============================================================

def main() -> None:
    """
    Run the Cybersecurity and Deepfake Multi-Agent System.
    """

    terminal_width = shutil.get_terminal_size(
        fallback=(100, 24)
    ).columns

    line_width = min(
        70,
        terminal_width - 1,
    )

    # ========================================================
    # APPLICATION HEADER
    # ========================================================

    print(
        "=" * line_width
    )

    print(
        "CYBERSECURITY & DEEPFAKE IMAGE ANALYSIS SYSTEM"
    )

    print(
        "=" * line_width
    )

    print(
        "\nHi! Please provide an image for analysis."
    )

    print(
        "\nThe image will be analysed for:"
    )

    print(
        "  • Cybersecurity threats"
    )

    print(
        "  • Possible deepfake manipulation"
    )

    print(
        "  • Evidence reliability"
    )

    print(
        "\nSupported formats:"
    )

    print(
        "  • JPG"
    )

    print(
        "  • JPEG"
    )

    print(
        "  • PNG"
    )

    print(
        "  • BMP"
    )

    print(
        "  • WEBP"
    )

    print(
        "\nType 'exit' at any prompt to stop."
    )

    print(
        "-" * line_width
    )

    # ========================================================
    # BUILD LANGGRAPH
    # ========================================================

    graph = build_graph()

    # ========================================================
    # MAIN LOOP
    # ========================================================

    while True:

        try:

            # =================================================
            # USER REQUEST
            # =================================================

            user_input = input(
                "\nEnter your request: "
            ).strip()

            if user_input.lower() in {
                "exit",
                "quit",
            }:

                print(
                    "\nExiting system."
                )

                break

            if not user_input:

                print(
                    "Please enter a request."
                )

                continue

            # =================================================
            # IMAGE PATH
            # =================================================

            image_path = input(
                "Enter image path: "
            ).strip()

            if image_path.lower() in {
                "exit",
                "quit",
            }:

                print(
                    "\nExiting system."
                )

                break

            if not image_path:

                print(
                    "Please enter an image path."
                )

                continue

            # =================================================
            # INITIAL STATE
            # =================================================

            initial_state = {
                "user_input":
                    user_input,

                "image_path":
                    image_path,

                "_start_time":
                    time.perf_counter(),

                "workflow_iterations":
                    0,

                "errors":
                    [],

                "fatal_error":
                    False,
            }

            # =================================================
            # PROCESSING MESSAGE
            # =================================================

            # Human developer modification:
            # Keep the processing message simple so the user
            # does not see internal routing information.

            print(
                "\nProcessing request..."
            )

            print(
                "Please wait..."
            )

            # =================================================
            # RUN LANGGRAPH WORKFLOW
            # =================================================

            result = graph.invoke(
                initial_state,
                config={"recursion_limit": 10}
            )

            # =================================================
            # CALCULATE PROCESSING TIME
            # =================================================

            # The graph normally calculates this value in the
            # final_response node. This is only a safety fallback.

            if "total_processing_time" not in result:

                start_time = initial_state.get(
                    "_start_time",
                    time.perf_counter(),
                )

                result[
                    "total_processing_time"
                ] = round(
                    time.perf_counter()
                    - start_time,
                    2,
                )

            # =================================================
            # FINAL RESULT
            # =================================================

            # Human developer modification:
            # Let graph.py handle both Partial and Error warnings
            # through the same final_response output.

            print_result(
                result
            )

        # ======================================================
        # KEYBOARD INTERRUPT
        # ======================================================

        except KeyboardInterrupt:

            print(
                "\n\nSystem interrupted."
            )

            break

        # ======================================================
        # UNEXPECTED SYSTEM ERROR
        # ======================================================

        except Exception as error:

            print(
                "\n" + "-" * line_width
            )

            print(
                "SYSTEM ERROR"
            )

            print(
                "-" * line_width
            )

            error_lines = wrap_text(
                str(error),
                65,
                continuation_indent=0,
            )

            for line in error_lines:

                print(
                    f"\nError: {line}"
                )

            print(
                "\nThe system returned to the main menu."
            )

            print(
                "-" * line_width
            )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()