"""Shared state used by the Multi-Agent System."""

# Any allows the shared state to store different types of
# values such as strings, numbers, lists, and dictionaries.

from typing import Any, TypedDict


# MASState defines the shared state used by LangGraph.
# The state acts as a central data structure where information
# produced by each workflow node is stored and passed to
# the next component.

class MASState(TypedDict, total=False):

    """
    Store shared workflow data including user input, image information,
    specialist findings, final assessment results, routing information,
    error details, and workflow execution tracking.
    """

    # ============================================================
    # User input
    # ============================================================

    # Stores the original request entered by the user.
    user_input: str

    # ============================================================
    # Image information
    # ============================================================

    # Stores the file path of the image submitted for analysis.
    image_path: str

    # ============================================================
    # Extracted image text
    # ============================================================

    # Stores text extracted from the submitted image by the OCR tool.
    image_text: str

    # ============================================================
    # Router information
    # ============================================================

    # Stores the routing information generated by the Router.
    route: str

    # Stores the specialist agents selected by the Dynamic Router
    # before specialist analysis begins.
    selected_agents: list[str]

    # Stores the status of the Dynamic Router.
    router_status: str

    # Stores the reason explaining why the specialist agents
    # were selected.
    routing_reason: str

    # ============================================================
    # Specialist agent findings
    # ============================================================

    # Stores the structured result returned by the
    # Cybersecurity Threat Detection Agent.
    cybersecurity_result: dict[str, Any]

    # Stores the structured result returned by the
    # Deepfake Detection Agent.
    deepfake_result: dict[str, Any]

    # Stores the structured result returned by the
    # Evidence Verification Agent.
    evidence_result: dict[str, Any]

    # ============================================================
    # Final assessment
    # ============================================================

    # Stores the cybersecurity risk score produced by
    # the Cybersecurity specialist analysis.
    cybersecurity_risk_score: float

    # Stores the possible deepfake manipulation risk score.
    deepfake_risk_score: float

    # Stores the reliability score of the available evidence.
    evidence_reliability_score: float

    # Stores the overall threat score calculated from
    # the available specialist results.
    overall_threat_score: float

    # Stores the overall risk category:
    # Low, Medium, or High.
    overall_risk_level: str

    # Stores the confidence level of the consolidated assessment.
    overall_confidence: str

    # Stores the important findings selected for the final response.
    key_findings: list[str]

    # Stores the consolidated reasoning produced for
    # the final assessment.
    overall_analysis: str

    # Stores limitations that explain the uncertainty
    # and boundaries of the automated analysis.
    limitations: list[str]

    # Stores practical safety recommendations for the user.
    recommended_action: list[str]

    # ============================================================
    # Conditional routing information
    # ============================================================

    # Stores the overall conditional routing path selected
    # by the workflow.
    routing_path: str

    # Stores the media-specific routing path selected
    # by the workflow.
    media_routing_path: str

    # Stores the explanation for the media-specific routing decision.
    media_routing_reason: str

    # ============================================================
    # Final response
    # ============================================================

    # Stores the complete formatted response that will
    # eventually be displayed to the user in the console.
    final_response: str

    # ============================================================
    # Error handling
    # ============================================================

    # Stores error messages generated by different workflow
    # components so failures can be tracked without crashing
    # the complete Multi-Agent System.
    errors: list[str]

    # Indicates whether a fatal workflow error has occurred.
    fatal_error: bool

    # Stores the explanation of a fatal error when one occurs.
    fatal_error_message: str

    # ============================================================
    # Workflow execution safeguard
    # ============================================================

    # Human developer modification:
    # This counter is used to prevent excessive workflow execution.
    # It allows the LangGraph workflow to stop safely if an unexpected
    # repeated execution occurs.
    workflow_iterations: int

    # Stores the timestamp when workflow processing begins.
    # This value is later used to calculate total processing time.
    _start_time: float

    # Stores the total time taken to process the complete
    # Multi-Agent System workflow.
    total_processing_time: float